// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaIy90FR6aVwkwl-yrg53pXDVRypCWKYU',
    appId: '1:479412690893:web:f6bb24b462b94ba6146e84',
    messagingSenderId: '479412690893',
    projectId: 'ez-parky-4a842',
    authDomain: 'ez-parky-4a842.firebaseapp.com',
    storageBucket: 'ez-parky-4a842.firebasestorage.app',
    measurementId: 'G-JV8SQF8PXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxHYb1XfcfRPjxAzdSthiuDOphuUXB0VM',
    appId: '1:479412690893:android:5b3a5b852d8ab752146e84',
    messagingSenderId: '479412690893',
    projectId: 'ez-parky-4a842',
    storageBucket: 'ez-parky-4a842.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1HCYQ0uJEf51zemgYgQr9JqXEO8vaQVw',
    appId: '1:479412690893:ios:961a4c5405fcfc33146e84',
    messagingSenderId: '479412690893',
    projectId: 'ez-parky-4a842',
    storageBucket: 'ez-parky-4a842.firebasestorage.app',
    iosBundleId: 'com.ezparky.ezParky',
  );
}
